Traceback (most recent call last):
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/ed-forecast/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig,ax = plt.subplots(figsize=(8,5))

scenarios = ['Population growth','111 capacity increase',
            'Ambulance capacity increase','GP capacity increase', 'Health of 2019']

for i,results in enumerate(scenario_results):
    
    if i==0:
        
        continue
    
    points,_ = sum_by_month(results)
    
    points_series = pd.Series(points)
    
    plt.plot(np.arange(-12, 96),
             points_series.rolling(window=4).mean().to_list()[:], 
             label = f'{scenarios[i]}')
    
    
points,_ = sum_by_month(scenario_results[0])

points_series = pd.Series(points)
    
plt.plot(np.arange(-12, 96),
         points_series.rolling(window=4).mean().to_list()[:],
         'g--', label = f'{scenarios[0]}')

    
y = np.arange(24000,29000,1000)    
plt.plot(np.zeros(len(y)),y, 'k--')

plt.legend(loc = 'lower left', fontsize=12)
plt.ylabel('Mean monthly ED attendances per CCG', fontsize=14)
plt.xlabel('Months since baseline', fontsize=14)
plt.xlim(0,48)

start, end = ax.get_xlim()
ax.xaxis.set_ticks(np.arange(-12, 50, 10))

#plt.ylim(24000,27000)
plt.tight_layout()
plt.savefig('forecast_scaled.png')
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [30][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m      8[0m [38;5;28;01mif[39;00m i[38;5;241m==[39m[38;5;241m0[39m:
[1;32m     10[0m     [38;5;28;01mcontinue[39;00m
[0;32m---> 12[0m points,_ [38;5;241m=[39m sum_by_month(results)
[1;32m     14[0m points_series [38;5;241m=[39m pd[38;5;241m.[39mSeries(points)
[1;32m     16[0m plt[38;5;241m.[39mplot(np[38;5;241m.[39marange([38;5;241m-[39m[38;5;241m12[39m, [38;5;241m96[39m),
[1;32m     17[0m          points_series[38;5;241m.[39mrolling(window[38;5;241m=[39m[38;5;241m4[39m)[38;5;241m.[39mmean()[38;5;241m.[39mto_list()[:], 
[1;32m     18[0m          label [38;5;241m=[39m [38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mscenarios[i][38;5;132;01m}[39;00m[38;5;124m'[39m)

[0;31mValueError[0m: too many values to unpack (expected 2)
ValueError: too many values to unpack (expected 2)

